import { User } from '../types/fitness.ts';

/**
 * FitBuddy AI Service
 * Communicates with backend Express proxy endpoints which call Google Gemini models.
 * - generateWorkout: uses Gemini Pro-tier model
 * - updateWorkoutPlan: uses Gemini Pro-tier model
 * - generateNutritionTip: uses Gemini Flash-tier model
 */

/**
 * Scenario 1: Generate 7-day personalized workout plan using Gemini Pro-tier model
 */
export async function generateWorkout(userData: User): Promise<string> {
  try {
    const response = await fetch('/api/generate-workout', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        age: userData.age,
        weight: userData.weight,
        goal: userData.goal,
        intensity: userData.intensity,
        experience_level: userData.experience_level,
        equipment: userData.equipment,
        session_time: userData.session_time,
      }),
    });

    const data = await response.json();

    if (!response.ok) {
      throw new Error(data.error || `HTTP error ${response.status}: Failed to generate workout plan`);
    }

    if (!data.plan) {
      throw new Error('No workout plan was generated by the AI model.');
    }

    return data.plan;
  } catch (err: any) {
    console.error('generateWorkout error:', err);
    throw new Error(err.message || 'Unable to connect to AI trainer service. Please verify your connection.');
  }
}

/**
 * Scenario 2: Update workout plan based on user feedback using Gemini Pro-tier model
 */
export async function updateWorkoutPlan(
  originalPlan: string,
  feedback: string
): Promise<string> {
  try {
    const response = await fetch('/api/update-workout', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        original_plan: originalPlan,
        user_feedback: feedback,
      }),
    });

    const data = await response.json();

    if (!response.ok) {
      throw new Error(data.error || `HTTP error ${response.status}: Failed to update workout plan`);
    }

    if (!data.updated_plan) {
      throw new Error('No revised plan was generated by the AI model.');
    }

    return data.updated_plan;
  } catch (err: any) {
    console.error('updateWorkoutPlan error:', err);
    throw new Error(err.message || 'Unable to refine plan based on feedback. Please try again.');
  }
}

/**
 * Scenario 3: Generate a concise nutrition or recovery tip using Gemini Flash-tier model
 */
export async function generateNutritionTip(
  user: User,
  planSummary: string
): Promise<string> {
  try {
    const response = await fetch('/api/generate-nutrition-tip', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        age: user.age,
        weight: user.weight,
        goal: user.goal,
        plan_summary: planSummary,
      }),
    });

    const data = await response.json();

    if (!response.ok) {
      throw new Error(data.error || `HTTP error ${response.status}: Failed to generate nutrition tip`);
    }

    if (!data.tip) {
      throw new Error('No tip returned.');
    }

    return data.tip;
  } catch (err: any) {
    console.error('generateNutritionTip error:', err);
    // Provide a smart local fallback tip if offline or rate-limited so UI is never left blank
    const fallbackTips: Record<string, string> = {
      'Weight Loss': 'Focus on a nutrient-dense 400-calorie deficit, drink 500ml water 20 minutes before meals, and prioritize lean protein to preserve lean muscle tissue.',
      'Muscle Gain': 'Target 1.6g to 2.2g of protein per kg of body weight daily and consume a 30g protein snack with complex carbohydrates within 60 minutes post-workout.',
      'General Wellness': 'Prioritize 7-8 hours of quality sleep, stay hydrated with 2.5-3 liters of water, and incorporate anti-inflammatory colorful berries and leafy greens.',
      'Endurance & Stamina': 'Replenish electrolytes after sessions exceeding 45 minutes, and fuel up with slow-digesting carbohydrates (like oats or brown rice) 2 hours prior.',
      'Strength & Power': 'Ensure adequate creatine and magnesium intake for muscle recovery, and rest at least 48 hours between training the same heavy compound muscle groups.',
    };

    return fallbackTips[user.goal] || 'Ensure balanced daily macronutrients, stay consistently hydrated throughout the day, and prioritize 7-9 hours of restorative sleep.';
  }
}
